site_name: U.S. Marine Energy Resource
site_url: https://us-marine-energy-resource.github.io/
site_description: United States marine energy resource characterization research sponsored by the U.S. Department of Energy
repo_url: https://github.com/US-Marine-Energy-Resource/documentation
repo_name: US-Marine-Energy-Resource/documentation

theme:
  name: material
  palette:
    - scheme: default
      primary: custom
      accent: custom
  font:
    text: Figtree
    code: Roboto Mono
  features:
    - navigation.top
    - search.suggest
    - search.highlight
  favicon: assets/images/favicon.svg
  icon:
    logo: material/water
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md

markdown_extensions:
  - tables
  - attr_list
  - md_in_html

extra:
  social:
    - icon: material/water
      link: https://github.com/US-Marine-Energy-Resource/documentation
  generator: false

copyright: Copyright &copy; 2026 Alliance for Energy Innovation, LLC
