"""MkDocs hook: flag images that haven't been run through the optimizer.

scripts/optimize_images.py does the actual work (resize, PNG quantization
via `imagequant`) and is run by hand whenever an image is added or replaced;
its output is committed to git, same as the tidal-plot images generated by
hooks/generate_tidal_plots.py. This hook does NOT re-run that pipeline on
every build -- doing real image processing on every `mkdocs build` would be
exactly the unnecessary, repeated work we want to avoid.

Instead this is a cheap guard, not a transform: it reads file size
(`os.path.getsize`) and PNG pixel dimensions (from the IHDR chunk, via
stdlib `struct` -- no image decode) for every media file MkDocs already
collected in `on_files`, and warns (or, with STRICT_IMAGE_SIZE=1, fails the
build) when a file exceeds the thresholds below. This module itself imports
nothing beyond the stdlib -- no Pillow/imagequant here -- so it costs a
handful of stat() calls per build regardless of what else is installed.
(Pillow and imagequant are in docs/requirements.txt only because
scripts/optimize_images.py needs them; that script is never invoked by this
hook or by `mkdocs build`.)

Thresholds are derived directly from scripts/optimize_images.py's output on
the current image corpus (17.66MB -> 5.50MB, ~69% reduction; post-optimize
files run 40KB-400KB, longest edge capped at 2400px) -- exceeding them means
"this image hasn't been run through the optimizer," not an independent size
policy. _SIZE_EXCEPTIONS covers legitimately high-entropy content (e.g. a
satellite basemap) that the optimizer can't shrink as far.

Set STRICT_IMAGE_SIZE=1 to fail the build instead of warning, mirroring the
REGENERATE_TIDAL_PLOTS env-var idiom in hooks/generate_tidal_plots.py:

    STRICT_IMAGE_SIZE=1 mkdocs build
"""

import logging
import os
import struct
from pathlib import Path

log = logging.getLogger("mkdocs.hooks.check_image_sizes")

MAX_BYTES = 450_000
MAX_DIMENSION = 2400

_SIZE_EXCEPTIONS = {
    # Satellite-basemap content (not line art) -- inherently high-entropy,
    # tops out around ~1.05MB even after best-effort quantization.
    "unstructured_grid_overview.png": 1_200_000,
}

_PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"


def _png_dimensions(path: Path) -> tuple[int, int] | None:
    """Read width/height from a PNG's IHDR chunk without decoding pixels."""
    try:
        with open(path, "rb") as f:
            header = f.read(24)
    except OSError:
        return None
    if len(header) < 24 or header[:8] != _PNG_SIGNATURE:
        return None
    width, height = struct.unpack(">II", header[16:24])
    return width, height


def on_files(files, config, **kwargs):
    strict = os.environ.get("STRICT_IMAGE_SIZE", "").strip() in {"1", "true", "yes"}
    problems: list[str] = []

    for file in files.media_files():
        path = Path(file.abs_src_path)
        if path.suffix.lower() not in {".png", ".jpg", ".jpeg"}:
            continue

        size = os.path.getsize(path)
        limit = _SIZE_EXCEPTIONS.get(path.name, MAX_BYTES)
        if size > limit:
            problems.append(
                f"{file.src_path}: {size:,} bytes exceeds {limit:,} byte limit"
            )

        if path.suffix.lower() == ".png":
            dims = _png_dimensions(path)
            if dims and max(dims) > MAX_DIMENSION:
                problems.append(
                    f"{file.src_path}: {dims[0]}x{dims[1]} exceeds "
                    f"{MAX_DIMENSION}px longest-edge limit"
                )

    if not problems:
        return files

    message = "check_image_sizes: unoptimized image(s) found:\n  " + "\n  ".join(
        problems
    ) + "\nRun: python scripts/optimize_images.py"

    if strict:
        raise SystemExit(f"\nERROR: {message}\n")

    log.warning(message)
    return files
