"""
Audit/Verify the US Wave hindcast S3 bucket and output markdown tables.

Usage:
    # Print current tables to stdout
    python check_wave_s3.py

    # Regenerate and overwrite the committed snapshot used by CI
    python check_wave_s3.py --update
"""

import argparse
import re
from dataclasses import dataclass, field
from pathlib import Path

import boto3
import pandas as pd
from botocore import UNSIGNED
from botocore.config import Config

BUCKET = "wpto-pds-us-wave"

SNAPSHOT_PATH = (
    Path(__file__).parent.parent / "docs" / "wave" / "hindcast" / "s3-inventory.md"
)

DOMAINS = {
    "v1.0.0": [
        "West_Coast",
        "Atlantic",
        "Hawaii",
        "Alaska",
        "CNMI_and_Guam",
        "Gulf_of_Mexico_and_Puerto_Rico",
        "virtual_buoy/West_Coast",
    ],
    "v1.0.1": [
        "West_Coast",
        "Atlantic",
        "Alaska",
        "Gulf_of_Mexico_and_Puerto_Rico",
    ],
}

LATEST_VERSIONS = {
    "West_Coast": "v1.0.1",
    "Atlantic": "v1.0.1",
    "Hawaii": "v1.0.0",
    "Alaska": "v1.0.1",
    "CNMI_and_Guam": "v1.0.0",
    "Gulf_of_Mexico_and_Puerto_Rico": "v1.0.1",
    "virtual_buoy/West_Coast": "v1.0.0",
}


@dataclass
class DomainInfo:
    version: str
    domain: str
    file_count: int
    year_min: int | None
    year_max: int | None
    file_pattern: str
    total_size_gb: float
    s3_path: str
    openei_url: str = field(init=False)

    def __post_init__(self):
        prefix = f"{self.version}/{self.domain}/"
        self.openei_url = (
            f"https://data.openei.org/s3_viewer?bucket={BUCKET}"
            f"&prefix={prefix.replace('/', '%2F')}"
        )


def list_domain(s3_client, version: str, domain: str) -> DomainInfo:
    prefix = f"{version}/{domain}/"
    paginator = s3_client.get_paginator("list_objects_v2")
    pages = paginator.paginate(Bucket=BUCKET, Prefix=prefix)

    files = []
    total_bytes = 0
    for page in pages:
        for obj in page.get("Contents", []):
            key = obj["Key"]
            size = obj["Size"]
            if size == 0:
                continue
            files.append(key)
            total_bytes += size

    years = []
    for f in files:
        m = re.search(r"(\d{4})\.h5$", f)
        if m:
            years.append(int(m.group(1)))

    pattern = ""
    if files:
        fname = files[0].split("/")[-1]
        pattern = re.sub(r"\d{4}", "{year}", fname)

    return DomainInfo(
        version=version,
        domain=domain,
        file_count=len(files),
        year_min=min(years) if years else None,
        year_max=max(years) if years else None,
        file_pattern=pattern,
        total_size_gb=total_bytes / 1e9,
        s3_path=f"s3://{BUCKET}/{prefix}",
    )


def build_markdown(verbose: bool = False) -> str:
    """Query S3 and return the full markdown string for both tables."""
    s3 = boto3.client("s3", config=Config(signature_version=UNSIGNED))

    rows = []
    for version, domains in DOMAINS.items():
        for domain in domains:
            if verbose:
                print(f"  Checking {version}/{domain}...", flush=True)
            info = list_domain(s3, version, domain)
            rows.append(
                {
                    "Version": info.version,
                    "Domain": info.domain,
                    "Files": info.file_count,
                    "Years": f"{info.year_min}–{info.year_max}"
                    if info.year_min
                    else "—",
                    "File Pattern": f"`{info.file_pattern}`"
                    if info.file_pattern
                    else "—",
                    "Size (GB)": f"{info.total_size_gb:.1f}",
                    "S3 Path": f"`{info.s3_path}`",
                    "Browse": f"[OpenEI]({info.openei_url})",
                }
            )

    df = pd.DataFrame(rows)

    latest_rows = []
    for domain, version in LATEST_VERSIONS.items():
        match = df[(df["Domain"] == domain) & (df["Version"] == version)]
        if not match.empty:
            latest_rows.append(match.iloc[0].to_dict())

    df_latest = pd.DataFrame(latest_rows)[
        ["Domain", "Version", "Years", "File Pattern", "Size (GB)", "Browse"]
    ]

    lines = [
        "<!-- This file is auto-generated by scripts/check_wave_s3.py --update -->",
        "<!-- Do not edit by hand. Run that command to regenerate. -->",
        "",
        "## Latest Version per Domain",
        "",
        df_latest.to_markdown(index=False),
        "",
        "",
        "## All Available Data",
        "",
        df.to_markdown(index=False),
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--update",
        action="store_true",
        help=f"Write output to {SNAPSHOT_PATH} instead of stdout",
    )
    args = parser.parse_args()

    content = build_markdown(verbose=True)

    if args.update:
        SNAPSHOT_PATH.write_text(content, encoding="utf-8")
        print(f"\nSnapshot written to {SNAPSHOT_PATH}")
    else:
        print(content)


if __name__ == "__main__":
    main()
