"""
Audit/Verify the US Wave hindcast S3 bucket and output markdown tables.

Usage:
    # Print current tables to stdout
    python check_wave_s3.py

    # Regenerate and overwrite the committed snapshot used by CI
    python check_wave_s3.py --update

    # Also regenerate the compact card summary snippet
    python check_wave_s3.py --update --card-summary
"""

import argparse
from pathlib import Path

import pandas as pd

from wave_s3 import (
    BUCKET,
    DOMAIN_LABELS,
    DOMAINS,
    LATEST_VERSIONS,
    list_domain,
    s3_client,
)

SNAPSHOT_PATH = (
    Path(__file__).parent.parent / "docs" / "wave" / "hindcast" / "s3-inventory.md"
)

CARD_SUMMARY_PATH = (
    Path(__file__).parent.parent / "docs" / "includes" / "wave-s3-summary.md"
)


def build_card_summary(rows: list[dict] | None = None) -> str:
    """Build a compact per-region size table for use in the homepage card snippet."""
    if rows is None:
        s3 = s3_client()
        rows = []
        for version, domains in DOMAINS.items():
            for domain in domains:
                info = list_domain(s3, version, domain)
                rows.append(
                    {
                        "Version": info.version,
                        "Domain": info.domain,
                        "Size (GB)": info.total_size_gb,
                    }
                )

    summary_rows = []
    for domain, version in LATEST_VERSIONS.items():
        match = next(
            (r for r in rows if r["Domain"] == domain and r["Version"] == version), None
        )
        if match:
            size_tb = match["Size (GB)"] / 1000
            summary_rows.append(
                {
                    "Region": DOMAIN_LABELS.get(domain, domain),
                    "Coverage": "1979–2020",
                    "Size": f"{size_tb:.1f} TB",
                }
            )

    total_tb = sum(r["Size (GB)"] for r in rows
                   if r["Domain"] in LATEST_VERSIONS
                   and r["Version"] == LATEST_VERSIONS[r["Domain"]]) / 1000

    df = pd.DataFrame(summary_rows)
    table = df.to_markdown(index=False)

    lines = [
        "<!-- auto-generated by scripts/check_wave_s3.py --card-summary -->",
        "<!-- Do not edit by hand. Run that command to regenerate. -->",
        "",
        table,
        "",
        f"**Total (latest versions): ~{total_tb:.1f} TB**",
        "",
    ]
    return "\n".join(lines)


def build_markdown(verbose: bool = False) -> str:
    """Query S3 and return the full markdown string for both tables."""
    s3 = s3_client()

    rows = []
    for version, domains in DOMAINS.items():
        for domain in domains:
            if verbose:
                print(f"  Checking {version}/{domain}...", flush=True)
            info = list_domain(s3, version, domain)
            rows.append(
                {
                    "Version": info.version,
                    "Domain": info.domain,
                    "Files": info.file_count,
                    "Years": f"{info.year_min}–{info.year_max}"
                    if info.year_min
                    else "—",
                    "File Pattern": f"`{info.file_pattern}`"
                    if info.file_pattern
                    else "—",
                    "Size (GB)": f"{info.total_size_gb:.1f}",
                    "S3 Path": f"`{info.s3_path}`",
                    "Browse": f"[OpenEI]({info.openei_url})",
                }
            )

    df = pd.DataFrame(rows)

    latest_rows = []
    for domain, version in LATEST_VERSIONS.items():
        match = df[(df["Domain"] == domain) & (df["Version"] == version)]
        if not match.empty:
            latest_rows.append(match.iloc[0].to_dict())

    df_latest = pd.DataFrame(latest_rows)[
        ["Domain", "Version", "Years", "File Pattern", "Size (GB)", "Browse"]
    ]

    lines = [
        "<!-- This file is auto-generated by scripts/check_wave_s3.py --update -->",
        "<!-- Do not edit by hand. Run that command to regenerate. -->",
        "",
        "## Latest Version per Domain",
        "",
        df_latest.to_markdown(index=False),
        "",
        "",
        "## All Available Data",
        "",
        df.to_markdown(index=False),
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--update",
        action="store_true",
        help=f"Write full inventory to {SNAPSHOT_PATH} instead of stdout",
    )
    parser.add_argument(
        "--card-summary",
        action="store_true",
        help=f"Write compact card summary snippet to {CARD_SUMMARY_PATH}",
    )
    args = parser.parse_args()

    content = build_markdown(verbose=True)

    if args.update:
        SNAPSHOT_PATH.write_text(content, encoding="utf-8")
        print(f"\nSnapshot written to {SNAPSHOT_PATH}")
    else:
        print(content)

    if args.card_summary:
        summary = build_card_summary()
        CARD_SUMMARY_PATH.write_text(summary, encoding="utf-8")
        print(f"Card summary written to {CARD_SUMMARY_PATH}")


if __name__ == "__main__":
    main()
